### ISSUE TITLE
Broken pipe (os error 32) when piping output to head

### ISSUE THREAD

**Issue by gingkapls** [Misterio77/flavours#16]
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:895:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

shows up sometimes whenever I pipe the output of `flavours info $(flavours current)` using head like this

`flavours info $(flavours current) | head -n<integer>`

The command works fine and the error can be avoided by redirecting it to /dev/null but thought I'd let you know just in case.

also running with env variable `RUST_BACKTRACE=1` doesn't provide a backtrace

**Comment by Misterio77** [comment]
Hmmm this seems to be [a problem with the print macro in Rust](https://github.com/rust-lang/rust/issues/46016).

Apparently, `head` closes the stream when it's done receiving the specified number of lines, and `println!` then unwraps that `Result` instead of moving it up, causing a panic instead of an `Result` i can handle to gracefully close the program.

Long story short, writing to `stdout` can fail and the widely used print feature Rust has won't handle it.

It seems the way to go would be replacing `print!`s with `write!`s, which do propagate `Result`s.


The possible workarounds seem to be your `/dev/null` piping, or piping `flavours info` through `cat` before piping it to head.

I'll probably get to it in the next few days/weeks, but feel free to write a patch if you have the time to spare ❤

**Comment by Misterio77** [comment]
This should be fixed in the commit https://github.com/Misterio77/flavours/commit/d958a604911b4a317e517c55e9cbc164e1d916fa. I'll push a new release soon!
